import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import logo  from '../public/icon/logo.svg' 
import SvgComponent from '../component/Pre-home'
import { useEffect, useRef } from 'react'


export default function Home() {
  const ref = useRef<HTMLDivElement>(null)
  const mask = useRef<HTMLDivElement>(null)
  useEffect(()=>{
    ref.current?.addEventListener("mousemove",(event)=>{
      event.preventDefault();
      console.log(event)
      var upX = event.clientX;
      var upY = event.clientY;
      // var mask = ('#mask1 circle')[0];
      mask.current?.setAttribute("cy", (upY - 5) + 'px');
      mask.current?.setAttribute("cx", (upX) + 'px');
    })
  },[ref,mask])  // trigger before use eff
 


  return (
    <div className={styles.container}>
      <Head>
        <title>C U TU!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/actkathonicon.png"/>
      </Head>
      
      <main className={styles.main}>
        <h1>ดีจ้า</h1>
        <h2>ดีจ้า</h2>
        <h3>ดีจ้า</h3>
      </main>

      <div className="pic" ref={ref}>
        <SvgComponent
        mask = {mask}
        />
      </div>

      <footer>

      </footer>

    </div>
  )
}
