import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef } from "react";
import Navbar from "../components/Navbar";
import Thumbnail from "../components/Thumbnail";
import Footer from "../components/Footer";
import { useState } from "react";
import Data, { Proovestate } from "../models/data_doc";

export default function Home() {
  const ref = useRef<HTMLDivElement>(null);
  const mask = useRef<HTMLDivElement>(null);
  const [page, setPage] = useState(1);

  const document: Data = {
    id: 64001,
    detailMoney: "12M",
    detailName: "โครงการปะลุกกะลิก",
    prooveState: Proovestate.UNMARK,
  };
  const document2: Data = {
    id: 64001,
    detailMoney: "12M",
    detailName: "โครงการมีนเองรักเจมส์นะจ๊ะ",
    prooveState: Proovestate.UNMARK,
  };
  const data = [document, document, document, document2, document, document];

  const onClickLeft = () => {
    if (page <= 1) {
      return;
    }
    setPage(page - 1);
  };

  const onClickRight = () => {
    if (page >= data.length - 3) {
      return;
    }
    setPage(page + 1);
  };
  return (
    <div className="h-screen overflow-scroll w-screen m-0 p-0">
      <Head>
        <title>C U TU!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/iconhome.png" />
      </Head>

      <div>
        <Navbar />
      </div>
      <div className="h-full">
      <div className="content flex justify-center place-items-center w-full h-full m-0 p-0">
        <div className={page <= 1 ? "opacity-0":""} onClick={onClickLeft}>
          <ion-icon name="chevron-back-outline" size="large"></ion-icon>
        </div>
        <Thumbnail currentPage={page} data={data} />
        <div className={page >= data.length - 3 ? "opacity-0":""} onClick={onClickRight}>
          <ion-icon name="chevron-forward-outline" size="large"></ion-icon>
        </div>
      </div >
        <Footer />
      </div>
    </div>
  );
}
